name: 'Recent Commits'
description: 'List of commits made since last push'
branding:
  icon: 'git-commit'
  color: 'blue'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  main-branch:
    description: 'Main branch to compare against'
    required: false
    default: 'main'
  last-push-branch:
    description: 'Branch pointing to the last commit made to the main branch'
    required: false
    default: 'last-push-to-main'
  author-file:
    description: 'File containing list of possible authors to notify'
    required: false
outputs:
  commits:
    description: 'List of commits made since last push'
    value: ${{ steps.get-commits.outputs.commits }}
  author-notify-id:
    description: 'Author of the pushed commits'
    value: ${{ steps.get-author.outputs.author-notify-id }}
  message:
    description: 'Aggregated message that can be sent to a message channel'
    value: ${{ steps.create-message.outputs.message }}
runs:
  using: 'composite'
  steps:
    - id: checkout
      name: 'Checkout'
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github-token }}
        fetch-depth: 0

    - id: ensure-branch-exists
      name: 'Ensure last-push-branch exists'
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: ${{ github.action_path }}/ensure-branch-exists.sh ${{ inputs.last-push-branch }}
      shell: bash

    - id: get-commits
      name: 'Get commits'
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        echo "commits<<EOF" >> $GITHUB_OUTPUT
        echo "$(${{ github.action_path }}/recent-commits.sh origin/${{ inputs.last-push-branch }} origin/${{ inputs.main-branch }})" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      shell: bash

    - id: get-author
      name: 'Get author'
      if: "${{ inputs.author-file != '' }}"
      run: echo "author-notify-id=$(${{ github.action_path }}/author.sh .github/${{ inputs.author-file }} ${{ github.actor }})" >> $GITHUB_OUTPUT
      shell: bash

    - id: create-message
      name: 'Create message'
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        COMMITS_OUTPUT: ${{ steps.get-commits.outputs.commits }}
        AUTHOR_OUTPUT: ${{ steps.get-author.outputs.author-notify-id }}
      run: |
        echo "message<<EOF" >> $GITHUB_OUTPUT
        echo "$(${{ github.action_path }}/create-message.sh ${{ github.server_url}} ${{ github.repository}} "$COMMITS_OUTPUT" "$AUTHOR_OUTPUT" ${{ github.actor }})" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      shell: bash

    - id: update-last-push-branch
      name: 'Update last-push-branch'
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: ${{ github.action_path }}/advance-last-push.sh ${{ inputs.last-push-branch }} ${{ inputs.main-branch }}
      shell: bash
