name: Publish

on:
  release:
    types: [published, edited]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Release with semantic tag like v1.0.3
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Setup git
        run: |
          git config --global user.name 'github_actions'
          git config --global user.email 'github_actions@users.noreply.github.com'

      - name: Make Tags
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: ./github/make-tags.sh
