name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Script tests
        run: test/test.sh
        shell: bash
